[package]
org = "ballerina"
name = "cloud"
version = "@toml.version@"
distribution= "2201.0.4"
repository = "https://github.com/ballerina-platform/module-ballerina-c2c"
license = ["Apache-2.0"]
keywords = ["cloud", "kubernetes", "docker", "k8s", "c2c"]
